
'use client';

import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { ScrollArea } from '../ui/scroll-area';

interface FaqModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const faqData = [
    {
        question: "How does the 'Search by Ingredient' feature work?",
        answer: "You can enter a comma-separated list of ingredients you have on hand, and our app will find recipes you can make. The more ingredients you provide, the more specific the results will be."
    },
    {
        question: "What is the AI Recipe Expert?",
        answer: "The AI Recipe Expert is a chat feature that helps you with specific recipes. You can ask it for ingredient substitutions, cooking technique clarifications, or suggestions for side dishes. You can access it from any recipe details page."
    },
    {
        question: "Can I save my favorite recipes?",
        answer: "This feature is coming soon! We are working on a cookbook feature that will allow you to save and organize your favorite recipes."
    },
    {
        question: "How do I share my own recipe?",
        answer: "If you are logged in, you can click the 'Share Recipe' button in the header. This will open a form where you can enter all the details of your recipe, including uploading a photo."
    },
    {
        question: "Where do the recipes come from?",
        answer: "Our recipes are sourced from a combination of TheMealDB, a large, public database of recipes, and original recipes generated by Google's Gemini AI. We also feature recipes shared by our user community."
    }
]

export function FaqModal({ isOpen, onClose }: FaqModalProps) {
  
  const handleDialogClose = (open: boolean) => {
    if (!open) {
        onClose();
    }
  }

  return (
    <Dialog open={isOpen} onOpenChange={handleDialogClose}>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>Frequently Asked Questions</DialogTitle>
          <DialogDescription>
            Find answers to common questions about the Dish Directory app.
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-96 pr-6">
            <Accordion type="single" collapsible className="w-full">
                {faqData.map((faq, index) => (
                    <AccordionItem value={`item-${index}`} key={index}>
                        <AccordionTrigger>{faq.question}</AccordionTrigger>
                        <AccordionContent>
                           <p className="text-muted-foreground">{faq.answer}</p>
                        </AccordionContent>
                    </AccordionItem>
                ))}
            </Accordion>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
